app:
  title: Scaffolded Backstage App
  baseUrl: https://backstage.codic.com.br

organization:
  name: Codic

backend:
  baseUrl: https://backstage.codic.com.br
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: https://backstage.codic.com.br
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: postgres
      port: 5432
      user: backstage
      password: spc1f1qhoeow3dzx
      database: backstage

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  ### Exemplo de proxy, você pode usar mais tarde
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

scaffolder:
  # Ações do Scaffolder, como o publish:github, precisam de configuração
  # Adicione o seu ownwer aqui
  # owner: 'user:default/icaro-rocha'
  
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    - type: file
      target: catalog-info.yaml
    - type: url
      target: 'https://github.com/icaroRochaP/robot-framework-automacao-api/blob/main/template.yaml'
      rules:
        - allow: [Template]
        
kubernetes:
  # Configure se você usar o plugin do Kubernetes
  #
permission:
  enabled: true