app:
  title: Scaffolded Backstage App
  baseUrl: https://backstage.codic.com.br

organization:
  name: Codic

backend:
  baseUrl: https://backstage.codic.com.br
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: https://backstage.codic.com.br
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true
  database:
    client: pg
    connection:
      host: postgres
      port: 5432
      user: backstage
      password: spc1f1qhoeow3dzx
      database: backstage

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

proxy:
  ### Exemplo de proxy, você pode usar mais tarde
  # endpoints:
  #   '/test':
  #     target: 'https://example.com'
  #     changeOrigin: true

techdocs:
  builder: 'local'
  generator:
    runIn: 'docker'
  publisher:
    type: 'local'

auth:
  providers:
    guest: {}

scaffolder:
  owner: icaro-rocha
  
catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template]
  locations:
    # O arquivo local agora é relativo a `app/`
    - type: file
      target: catalog-info.yaml
      
    # A URL para o seu template de automação de teste no GitHub
    - type: url
      target: 'https://raw.githubusercontent.com/icaroRochaP/robot-framework-automacao-api/main/template.yaml'
      rules:
        - allow: [Template]
        
kubernetes:
  permission:
    enabled: true