version: '3.8'

services:
  backstage:
    build: .
    ports:
      - '7007:7007'
    environment:
      # Variáveis de ambiente que o Backstage precisa para o banco de dados
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=spc1f1qhoeow3dzx
      - POSTGRES_DATABASE=backstage
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=backstage
      - POSTGRES_PASSWORD=spc1f1qhoeow3dzx
      - POSTGRES_DB=backstage
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: